import React from 'react';
import { 
  X, 
  Trash2, 
  FileSpreadsheet, 
  Code,
  CornerDownLeft, 
  Clock 
} from 'lucide-react';
import { HistoryItem } from '../types';
import { sound } from '../utils/audio';
import { useTranslation } from '../i18n/LanguageContext';

interface HistoryDrawerProps {
  isOpen: boolean;
  onClose: () => void;
  history: HistoryItem[];
  onClearHistory: () => void;
  onSelectHistoryItem: (item: HistoryItem) => void;
}

export const HistoryDrawer: React.FC<HistoryDrawerProps> = ({
  isOpen,
  onClose,
  history,
  onClearHistory,
  onSelectHistoryItem,
}) => {
  const { t } = useTranslation();
  if (!isOpen) return null;

  const exportCSV = () => {
    sound.playClick();
    const csvContent =
      'data:text/csv;charset=utf-8,Timestamp,Mode,Expression,Result\n' +
      history
        .map(
          (h) =>
            `"${new Date(h.timestamp).toISOString()}","${h.mode}","${h.expression.replace(/"/g, '""')}","${h.result}"`
        )
        .join('\n');
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', `calculator-history-${Date.now()}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const exportLaTeX = () => {
    sound.playClick();
    const latexContent =
      '% Generated by Calculator Pro Tape\n\\begin{align*}\n' +
      history
        .map((h) => `  ${h.expression.replace(/×/g, '\\times ').replace(/÷/g, '\\div ')} &= ${h.result} \\\\`)
        .join('\n') +
      '\n\\end{align*}';
    navigator.clipboard.writeText(latexContent);
  };

  return (
    <div className="fixed inset-0 z-50 flex justify-end bg-black/70 backdrop-blur-xs animate-fadeIn">
      <div 
        id="history-drawer-panel"
        className="w-full max-w-md bg-[#0b1329] border-l border-slate-800 h-full flex flex-col shadow-2xl text-slate-200"
      >
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b border-slate-800 bg-[#0b1329]/95">
          <div className="flex items-center gap-2.5">
            <Clock className="w-4 h-4 text-sky-400" />
            <h3 className="font-bold text-sm text-white">{t.history.title}</h3>
            <span className="text-xs px-2 py-0.5 rounded-full bg-slate-800 text-sky-300 font-mono">
              {history.length}
            </span>
          </div>

          <div className="flex items-center gap-1.5">
            {history.length > 0 && (
              <>
                <button
                  onClick={exportCSV}
                  className="p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 transition cursor-pointer"
                  title="CSV"
                >
                  <FileSpreadsheet className="w-4 h-4 text-emerald-400" />
                </button>
                <button
                  onClick={exportLaTeX}
                  className="p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 transition cursor-pointer"
                  title="LaTeX"
                >
                  <Code className="w-4 h-4 text-sky-400" />
                </button>
                <button
                  onClick={() => {
                    sound.playClear();
                    onClearHistory();
                  }}
                  className="p-2 rounded-xl bg-rose-500/10 hover:bg-rose-500/20 text-rose-400 transition cursor-pointer"
                  title={t.history.clear}
                >
                  <Trash2 className="w-4 h-4" />
                </button>
              </>
            )}
            <button
              onClick={onClose}
              className="p-2 rounded-xl hover:bg-slate-800 text-slate-400 hover:text-white transition cursor-pointer"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* List of items */}
        <div className="flex-1 overflow-y-auto p-4 space-y-3">
          {history.length === 0 ? (
            <div className="h-full flex flex-col items-center justify-center text-center text-slate-500 space-y-2">
              <Clock className="w-8 h-8 stroke-1 text-slate-600" />
              <p className="text-xs">{t.history.empty}</p>
            </div>
          ) : (
            history.map((item) => (
              <div
                key={item.id}
                onClick={() => onSelectHistoryItem(item)}
                className="p-3.5 rounded-xl bg-slate-900/60 border border-slate-800 hover:border-sky-500/40 transition cursor-pointer space-y-1.5 group shadow-sm hover:shadow-[0_0_15px_rgba(14,165,233,0.1)]"
              >
                <div className="flex items-center justify-between text-[10px] text-slate-500 font-mono">
                  <span>{new Date(item.timestamp).toLocaleTimeString()}</span>
                  <span className="uppercase text-sky-400/90 font-semibold">{item.mode}</span>
                </div>
                <div className="font-mono text-xs text-slate-400 truncate">
                  {item.expression} =
                </div>
                <div className="flex items-center justify-between">
                  <div className="font-mono text-base font-bold text-white group-hover:text-sky-300 transition">
                    {item.result}
                  </div>
                  <span className="text-[11px] text-slate-500 flex items-center gap-1 opacity-0 group-hover:opacity-100 transition text-sky-400">
                    <CornerDownLeft className="w-3 h-3 text-sky-400" />
                    {t.common.insert}
                  </span>
                </div>
              </div>
            ))
          )}
        </div>

        {/* Footer */}
        <div className="p-3.5 border-t border-slate-800 text-[11px] text-slate-500 font-mono text-center bg-[#020617]">
          {t.history.clickToInsert}
        </div>
      </div>
    </div>
  );
};
